import os
from cold.models import autogenerated as cold
from gleaned import DataHarvester, FileSource, WMIDataSource
from echoed import base
import json

# Create a digital twin
my_twin = base.DigitalTwin(
    metamodel = cold.CR2032(),
    data_sources = [
        WMIDataSource(refresh_interval = 1),
        FileSource(file_path=os.path.abspath(f"battery_data.parquet"), file_type=f"parquet"),
        FileSource(file_path=os.path.abspath(f"battery_data.csv"), file_type=f"csv"),
        FileSource(file_path=os.path.abspath(f"battery_data.json"), file_type=f"json")
    ]
)

print("Digital twin initialized:", my_twin)

data = my_twin.get_live_status()

json_ld = my_twin.metamodel.to_jsonld()
print(json.dumps(json_ld, indent=4))

